project:
  type: website
  output-dir: _site

website:
  title: "Machine Learning A2"
  navbar:
    left:
      - text: "Journal"
        file: notebooks/journal.ipynb
      - text: "Implementation"
        file: implementation.ipynb
      - text: "Models"
      - text: "Presentation"
        file: presentation.ipynb
        menu:
          - text: "Logistic Regression"
            file: notebooks/log_reg.ipynb
          - text: "Multi-Layer Perceptron"
            file: notebooks/mlp.ipynb
      - text: "Utils"
        menu:
          - text: "Preprocessing"
            file: notebooks/preprocessing_utils.ipynb
          - text: "Training and Evaluation"
            file: notebooks/models_utils.ipynb
format:
  html:
    theme: pulse
    toc: true
    code-fold: false
